package com.kite.mnemoai.model.data

import com.kite.mnemoai.model.recite.PronounceType
import com.kite.mnemoai.model.statistic.DateInterval
import com.kite.mnemoai.model.statistic.DateIntervalType
import java.time.LocalTime

data class DeepseekAiSettings(
    val apiKey: String = "",
    val modelType: String = UserSettingDefaults.DEFAULT_MODEL_TYPE,
    val enableThinking: Boolean = false,
)

data class UserSetting(
    val newLearningWordCount: Int,
    val lightDarkModel: ThemeType,
    val statisticDateIntervalType: DateIntervalType,
    val statisticDateInterval: DateInterval,
    val currentAiProvider: AiProvider,
    val deepseekSettings: DeepseekAiSettings,
    val enableReminder: Boolean,
    val reminderTime: LocalTime,
    val enableAutoGenerateDailyWordExtract: Boolean,
    val aiPrompts: Map<AiPromptType, AiPromptSet>,
    val pronounceType: PronounceType,
    val autoPronounce: Boolean
)
