package com.kite.mnemoai.model.repository

import com.kite.mnemoai.model.Result
import com.kite.mnemoai.model.data.AiPromptSet
import com.kite.mnemoai.model.data.AiPromptType
import com.kite.mnemoai.model.data.AiProvider
import com.kite.mnemoai.model.data.ThemeType
import com.kite.mnemoai.model.data.UserSetting
import com.kite.mnemoai.model.recite.PronounceType
import com.kite.mnemoai.model.statistic.DateInterval
import com.kite.mnemoai.model.statistic.DateIntervalType
import kotlinx.coroutines.flow.Flow
import java.time.LocalDate
import java.time.LocalTime

interface UserSettingRepository {
    val userSetting: Flow<UserSetting>

    suspend fun setNewLearningWordCount(targetCount: Int)

    suspend fun setLightDarkModel(model: ThemeType)

    suspend fun setApiKey(apiKey: String)

    suspend fun setDeepseekModelType(modelType: String)

    suspend fun setEnableThinking(enableThinking: Boolean)

    suspend fun setAiProvider(provider: AiProvider)

    suspend fun setReminderTime(reminderTime: LocalTime)

    suspend fun setEnableReminder(enableReminder: Boolean)

    suspend fun setDateInterval(type: DateIntervalType, dateInterval: DateInterval)

    suspend fun setEnableAutoGenerateDailyWordExtract(enableAutoGenerateDailyWordExtract: Boolean)

    suspend fun setAiPrompts(aiPrompts: Map<AiPromptType, AiPromptSet>)

    suspend fun setPronounceType(pronounceType: PronounceType)

    suspend fun setAutoPronounce(enableAutoPronounce: Boolean)
}
