package com.kite.mnemoai.datastore

import androidx.datastore.core.DataStore
import com.kite.mnemoai.model.data.AiPromptSet
import com.kite.mnemoai.model.data.AiPromptType
import com.kite.mnemoai.model.data.AiProvider
import com.kite.mnemoai.model.data.ThemeType
import com.kite.mnemoai.model.recite.PronounceType
import com.kite.mnemoai.model.statistic.DateInterval
import com.kite.mnemoai.model.statistic.DateIntervalType
import jakarta.inject.Inject
import kotlinx.coroutines.flow.map
import java.time.LocalTime

class UserSettingDataSource @Inject constructor(
    private val userPreferences: DataStore<UserPreferences>
) {
    val userSetting = userPreferences.data.map { it.toDomain() }

    suspend fun setNewLearningWordCount(targetCount: Int) {
        userPreferences.updateData { it.toBuilder().setNewLearningWordCount(targetCount).build() }
    }

    suspend fun setLightDarkModel(model: ThemeType) {
        userPreferences.updateData { it.toBuilder().setLightDarkMode(model.toProto()).build() }
    }

    suspend fun setApiKey(apiKey: String) {
        userPreferences.updateData { preferences ->
            preferences.toBuilder()
                .setDeepseekSettings(
                    preferences.deepseekSettings.toBuilder().setApiKey(apiKey).build()
                )
                .build()
        }
    }

    suspend fun setDeepseekModelType(modelType: String) {
        userPreferences.updateData { preferences ->
            preferences.toBuilder()
                .setDeepseekSettings(
                    preferences.deepseekSettings.toBuilder().setModelType(modelType).build()
                )
                .build()
        }
    }

    suspend fun setEnableThinking(enableThinking: Boolean) {
        userPreferences.updateData { preferences ->
            preferences.toBuilder()
                .setDeepseekSettings(
                    preferences.deepseekSettings.toBuilder().setEnableThinking(enableThinking).build()
                )
                .build()
        }
    }

    suspend fun setAiProvider(provider: AiProvider) {
        userPreferences.updateData { it.toBuilder().setAiProvider(provider.toProto()).build() }
    }

    suspend fun setReminderTime(reminderTime: LocalTime) {
        userPreferences.updateData { it.toBuilder().setReminderTime(reminderTime.toString()).build() }
    }

    suspend fun setEnableReminder(enableReminder: Boolean) {
        userPreferences.updateData { it.toBuilder().setEnableReminder(enableReminder).build() }
    }

    suspend fun setEnableAutoGenerateDailyWordExtract(enableAutoGenerateDailyWordExtract: Boolean){
        userPreferences.updateData { it.toBuilder().setEnableAutoGenerateDailyWordExtract(enableAutoGenerateDailyWordExtract).build() }
    }

    suspend fun setAiPrompts(aiPrompts: Map<AiPromptType, AiPromptSet>) {
        userPreferences.updateData { preferences ->
            val builder = preferences.toBuilder().clearAiPrompts()
            aiPrompts.forEach { (type, set) ->
                builder.addAiPrompts(
                    AiPromptEntryProto.newBuilder()
                        .setType(type.toProto())
                        .setSet(
                            AiPromptSetProto.newBuilder()
                                .setSystemPrompt(set.systemPrompt)
                                .setUserPrompt(set.userPrompt)
                                .build()
                        )
                        .build()
                )
            }
            builder.build()
        }
    }

    suspend fun setDateInterval(type: DateIntervalType, interval: DateInterval) {
        userPreferences.updateData { preferences ->
            preferences.toBuilder()
                .setStatisticDateIntervalType(type.toProto())
                .setStatisticDateInterval(
                    StatisticDateInterval.newBuilder()
                        .setStartTime(interval.startDate.toString())
                        .setEndTime(interval.endDate.toString())
                        .build()
                ).build()
        }
    }

    suspend fun setPronounceType(type: PronounceType){
        userPreferences.updateData { it.toBuilder().setPronounceType(type.toProto()).build() }
    }

    suspend fun setAutoPronounce(enableAutoPronounce: Boolean){
        userPreferences.updateData { it.toBuilder().setAutoPronounce(enableAutoPronounce).build() }
    }
}
