package com.kite.mnemoai.datastore

import com.kite.mnemoai.model.data.AiPromptSet
import com.kite.mnemoai.model.data.AiPromptType
import com.kite.mnemoai.model.data.AiProvider
import com.kite.mnemoai.model.data.DeepseekAiSettings
import com.kite.mnemoai.model.data.ThemeType
import com.kite.mnemoai.model.data.UserSetting
import com.kite.mnemoai.model.data.UserSettingDefaults
import com.kite.mnemoai.model.recite.PronounceType
import com.kite.mnemoai.model.statistic.DateInterval
import com.kite.mnemoai.model.statistic.DateIntervalType
import java.time.LocalDate
import java.time.LocalTime

fun UserPreferences.toDomain(): UserSetting = UserSetting(
    newLearningWordCount = newLearningWordCount.takeIf { it > 0 }
        ?: UserSettingDefaults.NEW_LEARNING_WORD_COUNT,
    lightDarkModel = lightDarkMode.toDomain(),
    statisticDateIntervalType = statisticDateIntervalType.toDomain(),
    statisticDateInterval = DateInterval(
        parseIntervalDate(statisticDateInterval.startTime, LocalDate.now().minusDays(7)),
        parseIntervalDate(statisticDateInterval.endTime, LocalDate.now())
    ),
    currentAiProvider = aiProvider.toDomain(),
    deepseekSettings = if (hasDeepseekSettings()) deepseekSettings.toDomain()
        else UserSettingDefaults.DEFAULT_DEEPSEEK_SETTINGS,
    enableReminder = enableReminder,
    reminderTime = reminderTime.ifEmpty { UserSettingDefaults.REMINDER_TIME.toString() }
        .let(LocalTime::parse),
    enableAutoGenerateDailyWordExtract = enableAutoGenerateDailyWordExtract,
    aiPrompts = UserSettingDefaults.DEFAULT_AI_PROMPTS + aiPromptsList.associate { entry ->
        entry.type.toDomain() to AiPromptSet(entry.set.systemPrompt, entry.set.userPrompt)
    },
    pronounceType = pronounceType.toDomain(),
    autoPronounce = if (hasAutoPronounce()) autoPronounce else UserSettingDefaults.autoPronounce
)

fun AiPromptTypeProto?.toDomain(): AiPromptType = when (this) {
    AiPromptTypeProto.AI_PROMPT_TYPE_WORD_EXTRACT -> AiPromptType.WORD_EXTRACT
    AiPromptTypeProto.AI_PROMPT_TYPE_CHAT -> AiPromptType.CHAT
    else -> AiPromptType.WORD_EXTRACT
}

fun AiPromptType.toProto(): AiPromptTypeProto = when (this) {
    AiPromptType.WORD_EXTRACT -> AiPromptTypeProto.AI_PROMPT_TYPE_WORD_EXTRACT
    AiPromptType.CHAT -> AiPromptTypeProto.AI_PROMPT_TYPE_CHAT
}

fun ThemeTypeProto?.toDomain(): ThemeType = when (this) {
    ThemeTypeProto.DAY -> ThemeType.DAY
    ThemeTypeProto.NIGHT -> ThemeType.NIGHT
    else -> ThemeType.FOLLOW_SYS
}

fun ThemeType.toProto(): ThemeTypeProto = when (this) {
    ThemeType.FOLLOW_SYS -> ThemeTypeProto.FOLLOW_SYS
    ThemeType.DAY -> ThemeTypeProto.DAY
    ThemeType.NIGHT -> ThemeTypeProto.NIGHT
}

fun StatisticDateIntervalType?.toDomain(): DateIntervalType = when (this) {
    StatisticDateIntervalType.INTHELASTMONTH -> DateIntervalType.IN_THE_LAST_MONTH
    StatisticDateIntervalType.INTHELASTTHREEMONTH -> DateIntervalType.IN_THE_LAST_THREE_MONTH
    StatisticDateIntervalType.CUSTOM -> DateIntervalType.CUSTOM
    else -> DateIntervalType.IN_THE_LAST_SEVEN_DAY
}

fun DateIntervalType.toProto(): StatisticDateIntervalType = when (this) {
    DateIntervalType.IN_THE_LAST_MONTH -> StatisticDateIntervalType.INTHELASTMONTH
    DateIntervalType.IN_THE_LAST_THREE_MONTH -> StatisticDateIntervalType.INTHELASTTHREEMONTH
    DateIntervalType.CUSTOM -> StatisticDateIntervalType.CUSTOM
    DateIntervalType.IN_THE_LAST_SEVEN_DAY -> StatisticDateIntervalType.INTHELASTSEVENDAY
}

fun DeepseekSettings.toDomain(): DeepseekAiSettings = DeepseekAiSettings(
    apiKey = apiKey,
    modelType = modelType,
    enableThinking = enableThinking
)

fun AiProviderProto?.toDomain(): AiProvider = AiProvider.DEEPSEEK

fun AiProvider.toProto(): AiProviderProto = AiProviderProto.AI_PROVIDER_DEEPSEEK

fun PronounceTypeProto.toDomain() = when(this){
    PronounceTypeProto.UNRECOGNIZED,
    PronounceTypeProto.PRONOUNCE_TYPE_UNSPECIFIED,
    PronounceTypeProto.PRONOUNCE_TYPE_USA ->
        PronounceType.USA
    PronounceTypeProto.PRONOUNCE_TYPE_UK ->
        PronounceType.UK
}

fun PronounceType.toProto() = when(this){
    PronounceType.USA -> PronounceTypeProto.PRONOUNCE_TYPE_USA
    PronounceType.UK -> PronounceTypeProto.PRONOUNCE_TYPE_UK
}

private fun parseIntervalDate(value: String, default: LocalDate): LocalDate =
    value.ifEmpty { default.toString() }.let(LocalDate::parse)
