package com.kite.domain

import com.kite.mnemoai.model.repository.AiMnemonicRepository
import com.kite.mnemoai.model.repository.UserSettingRepository
import com.kite.mnemoai.model.repository.WordRepository
import jakarta.inject.Inject
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import java.time.LocalDate
import javax.inject.Singleton

@Singleton
class AutoGenerateDailyWordExtractUseCase @Inject constructor(
    private val wordRepository: WordRepository,
    private val userSettingRepository: UserSettingRepository,
    private val aiMnemonicRepository: AiMnemonicRepository
) {
    private val chunkSize = 5
    private val mutex = Mutex()

    suspend operator fun invoke() = mutex.withLock {
        val userSetting = userSettingRepository.userSetting.first()
        if (!userSetting.enableAutoGenerateDailyWordExtract) return@withLock
        if (userSetting.deepseekSettings.apiKey.isBlank()) return@withLock

        val date = LocalDate.now().toString()
        val pendingWordDetails = wordRepository.getUnfinishedWordDetailInfos(date)
            .filter { it.extract == null }
        if (pendingWordDetails.isEmpty()) return@withLock

        pendingWordDetails.chunked(chunkSize).forEach { chunk ->
            aiMnemonicRepository.generateWordExtract(chunk)
        }
    }
}
