package com.kite.domain

import com.kite.mnemoai.model.dayplan.DayPlanWord
import com.kite.mnemoai.model.repository.StatisticsRepository
import com.kite.mnemoai.model.repository.UserSettingRepository
import com.kite.mnemoai.model.repository.WordRepository
import jakarta.inject.Inject
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import java.time.LocalDate
import javax.inject.Singleton

@Singleton
class SetDailyReciteWordUseCase @Inject constructor(
    private val wordRepository: WordRepository,
    private val statisticsRepository: StatisticsRepository,
    private val userSettingRepository: UserSettingRepository,
    private val autoGenerateDailyWordExtractUseCase: AutoGenerateDailyWordExtractUseCase
) {
    private val mutex = Mutex()

    suspend operator fun invoke() {
        mutex.withLock {
            val date = LocalDate.now().toString()
            val dayPlanWords = statisticsRepository.getDayPlanWordsByDate(date)
            val newLearningWords = dayPlanWords.filter { it.type == 0 }
            val newLearningFinishedWord = newLearningWords.filter { it.status == 1 }
            val newLearningWordCount = userSettingRepository.userSetting.first().newLearningWordCount

            val reviewingWords = dayPlanWords.filter { it.type == 1 }
            val reviewingWordMap = reviewingWords.associateBy { it.wordId }
            val reviewWordIds = wordRepository.selectTodayReviewingWordEntities(date)
            val unselectedReviewingWordIds = reviewWordIds.filter { reviewingWordMap[it] == null }

            val reviewDayPlanWords = unselectedReviewingWordIds.map { reviewWord ->
                DayPlanWord(
                    reviewWord, date,
                    1, 0,
                    0, 0,
                    0, null
                )
            }

            if (newLearningWords.size < newLearningWordCount) {
                val newLearningWordIds = wordRepository.addTodayNewLearningWordEntities(
                    newLearningWordCount - newLearningWords.size,
                    date,
                    dayPlanWords.map { it.wordId }
                )
                val newDayPlanWords = newLearningWordIds.map { newLearningWordId ->
                    DayPlanWord(
                        newLearningWordId, date,
                        0, 0,
                        0, 0,
                        0, null
                    )
                }
                val allDayPlanWord = newDayPlanWords + reviewDayPlanWords
                statisticsRepository.addNewLearningDayPlanWords(allDayPlanWord)
            } else if (newLearningWords.size > newLearningWordCount) {
                if (newLearningFinishedWord.size < newLearningWordCount) {
                    statisticsRepository.deleteExceedDayPlanWords(
                        newLearningWords.size - newLearningWordCount
                    )
                }
            }
        }
        autoGenerateDailyWordExtractUseCase()
    }
}
