package com.kite.mnemoai.mine

import com.kite.mnemoai.model.data.AiProvider
import com.kite.mnemoai.model.data.ThemeType
import java.time.LocalTime

class MineUIState(
    val dayNightMode: ThemeType,
    val aiProvider: AiProvider?,
    val apikey: String?,
    val enableThinking: Boolean,
    val deepseekModelType: String?,
    val enableReminder: Boolean,
    val reminderTime: LocalTime,
    val enableAutoGenerateDailyWordExtract: Boolean
)
