package com.kite.mnemoai.mine

import android.content.Context
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.kite.domain.AutoGenerateDailyWordExtractUseCase
import com.kite.mnemoai.sync.StudyReminderScheduler
import com.kite.mnemoai.model.Result
import com.kite.mnemoai.model.data.AiProvider
import com.kite.mnemoai.model.data.ThemeType
import com.kite.mnemoai.model.repository.AiMnemonicRepository
import com.kite.mnemoai.model.repository.UserSettingRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.time.Duration
import java.time.LocalTime
import javax.inject.Inject

@HiltViewModel
class MineViewModel @Inject constructor(
    private val userSettingRepository: UserSettingRepository,
    private val aiMnemonicRepository: AiMnemonicRepository,
    private val autoGenerateDailyWordExtractUseCase: AutoGenerateDailyWordExtractUseCase
) : ViewModel() {
    private val _uiStatus = MutableStateFlow<MineUIState?>(null)
    val uIStatus get() = _uiStatus.asStateFlow()
    private val _apiTestResult = MutableSharedFlow<Result<String>>()
    val apiTestResult: SharedFlow<Result<String>> = _apiTestResult.asSharedFlow()
    private var dayNightMode: ThemeType = ThemeType.FOLLOW_SYS
    private var aiProvider: AiProvider? = null
    private var apiKey: String? = null
    private var enableThinking: Boolean = false
    private var deepseekModelType: String? = null
    private var enableReminder: Boolean = false
    private var reminderTime: LocalTime = LocalTime.of(8, 0)
    private var enableAutoGenerateDailyWordExtract: Boolean = false

    init {
        viewModelScope.launch {
            userSettingRepository.userSetting.collect { userSetting ->
                dayNightMode = userSetting.lightDarkModel
                apiKey = userSetting.deepseekSettings.apiKey
                aiProvider = userSetting.currentAiProvider
                enableThinking = userSetting.deepseekSettings.enableThinking
                deepseekModelType = userSetting.deepseekSettings.modelType
                enableReminder = userSetting.enableReminder
                reminderTime = userSetting.reminderTime
                enableAutoGenerateDailyWordExtract = userSetting.enableAutoGenerateDailyWordExtract
                updateUIStatus()
            }
        }
    }

    fun apiKeyTest(apiKey: String) {
        viewModelScope.launch {
            _apiTestResult.emit(Result.Loading)
            val result = aiMnemonicRepository.apiKeyTest(apiKey)
            if (result is Result.Success) {
                saveApiKey(apiKey)
            }
            _apiTestResult.emit(result)
        }
    }

    fun saveAiProvider(aiProvider: AiProvider) {
        viewModelScope.launch {
            userSettingRepository.setAiProvider(aiProvider)
        }
    }

    fun saveApiKey(apiKey: String?) {
        viewModelScope.launch {
            userSettingRepository.setApiKey(apiKey ?: "")
        }
    }

    fun saveLightDarkModel(lightDarkModel: ThemeType, setTheme: () -> Unit) {
        viewModelScope.launch {
            userSettingRepository.setLightDarkModel(lightDarkModel)
            setTheme.invoke()
        }
    }

    fun saveSubModel(modelType: String) {
        viewModelScope.launch {
            userSettingRepository.setDeepseekModelType(modelType)
        }
    }

    suspend fun loadModels(): Result<List<String>> = aiMnemonicRepository.getModelList()

    fun currentModelType(): String? = deepseekModelType

    fun saveThinking(boolean: Boolean){
        viewModelScope.launch {
            userSettingRepository.setEnableThinking(boolean)
        }
    }

    fun setEnableReminder(context: Context, boolean: Boolean){
        saveEnableReminder(boolean)
        if(boolean){
            var duration = Duration.between(LocalTime.now(), reminderTime)
            if (duration.isNegative) {
                duration = duration.plusDays(1)
            }
            StudyReminderScheduler.setStudyReminder(context, duration)
        }else{
            StudyReminderScheduler.disableStudyReminder(context)
        }

    }

    private fun saveEnableReminder(boolean: Boolean){
        viewModelScope.launch {
            userSettingRepository.setEnableReminder(boolean)
        }
    }

    fun setReminderTime(context: Context, reminderTime: LocalTime){
        saveReminderTime(reminderTime)
        var duration = Duration.between(LocalTime.now(), reminderTime)
        if (duration.isNegative) {
            duration = duration.plusDays(1)
        }
        StudyReminderScheduler.setStudyReminder(context, duration)
    }

    private fun saveReminderTime(reminderTime: LocalTime){
        viewModelScope.launch {
            userSettingRepository.setReminderTime(reminderTime)
        }
    }

    fun saveEnableAutoGenerateDailyWordExtract(boolean: Boolean){
        viewModelScope.launch {
            userSettingRepository.setEnableAutoGenerateDailyWordExtract(boolean)
            autoGenerateDailyWordExtractUseCase()
        }
    }

    private fun updateUIStatus() {
        _uiStatus.value =
            MineUIState(
                dayNightMode,
                aiProvider,
                apiKey,
                enableThinking,
                deepseekModelType,
                enableReminder,
                reminderTime,
                enableAutoGenerateDailyWordExtract)
    }

}
